### ISSUE TITLE
OCR API Send Bounding Box to Search?

### ISSUE THREAD

**Issue by SeaDude** [Azure-Samples/cognitive-services-REST-api-samples#108]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ X] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Question

Is it possible to send the OCR API a specific bounding box area to analyze? 

- **Example**:
  - I have a huge image (4000px X 3000px) with text sprinkled throughout. 
  - I'm only interested in text in a certain region (300px X 300px) in each image (think title block on large engineering document)
  - Is there a way to run OCR on ONLY a given bounding box area of each image?

Thank you

**Comment by SeaDude** [comment]
Any takers?

**Comment by SeaDude** [comment]
Anyone?

**Comment by wiazur** [comment]
Hi @SeaDude , thanks for the query. Sorry this repo was not being maintained too often. But if you still have your question, I can help you. Are you trying to avoid the time it would take to scan the entire image? Or share more details... thanks.

**Comment by SeaDude** [comment]
Hi @wiazur, all good, thanks for reaching out.

The use case involves thousands of images that have LOTS of handdrawn text all over the image (very old engineering drawings). I just want to focus on a particular area (the title block) to grab the metadata about the print (who drew it, date of drawing, date of revision, etc.). 

When I run the whole image through the API, the results are too much. Ideally, I'd like to say "read only from X pixel to X1 pixel and Y pixel to Y1 pixel" (like a bounding box). 

Do you think this is possible with the API or would I need to do some preprocessing and only send the titleblock image?

**Comment by PatrickFarley** [comment]
Hi @SeaDude , 
This feature isn't built into the Computer Vision API, but you should be able to use a third-party library to programmatically crop each image before performing OCR.

**Comment by wiazur** [comment]
@SeaDude which API call were you using for OCR, Recognize Text or Batch read File? And is the title block always at the top of the image or could it potentially be anywhere?

**Comment by SeaDude** [comment]
Hi @wiazur, using Recognize Text. Title block is always in the bottom, right corner of the image.

**Comment by SeaDude** [comment]
Hi @wiazur, thanks for continuing the chat. I'm using Recognize Text. Title block is always in the bottom, right corner of the image within a predicatable bounding box size.

Hi @PatrickFarley, the challenge is that the entire image needs to be associated with the metadata pulled from the title block. I'm trying to get away from creating a complex pipeline of crop image-->store cropped image-->associate cropped image with original-->send cropped image to API-->Get metadata--> Associate metadata with original image--> etc.

Challenging!

**Comment by wiazur** [comment]
Hi @SeaDude, what language are you using and would you consider using an SDK or does it need to be a REST call?

**Comment by SeaDude** [comment]
Believe it or not, I was using Power Automate (the artist formerly known as "Flow"), another Microsoft product to make things happen. Being a citizen dev, I'm not formally trained in any particular language...unless "hardcore low-code" is considered a lingo :)

I'm up for scripting a solution in python if need be.

**Comment by wiazur** [comment]
Hi @SeaDude, not sure if you still need a solution, but I found one using the Computer Vision SDK. We use the [Batch Read File API](https://docs.microsoft.com/en-us/python/api/azure-cognitiveservices-vision-computervision/azure.cognitiveservices.vision.computervision.operations.computervisionclientoperationsmixin?view=azure-python#batch-read-file-in-stream-image--custom-headers-none--raw-false--callback-none----operation-config-). 

This sample will take in a list of images with text, upload them, crop them around the last line of text (location is adjustable) and then run the API on the list of cropped images. I'll include the images here if you wanted to download and use, but feel free to use your own as well. The images are identical for the sake of testing (and showing a crop in the exact same place).

Here is the sample:
https://github.com/Azure-Samples/cognitive-services-quickstart-code/blob/master/python/ComputerVision/ExtractText.py 

![coffee1](https://user-images.githubusercontent.com/38537084/74498718-684a9280-4e96-11ea-8fc7-3890a7c1f01d.jpg)
![coffee2](https://user-images.githubusercontent.com/38537084/74498719-68e32900-4e96-11ea-954d-e8f65296f08f.jpg)

**Comment by SeaDude** [comment]
Wow @wiazur, thank you for this information! This looks like exactly what I needed. I'm going to dive in and test today. 
Take care

**Comment by SeaDude** [comment]
Hm. The [OCR API docs](https://westus.dev.cognitive.microsoft.com/docs/services/5adf991815e1060e6355ad44/operations/2afb498089f74080d7ef85eb) are quite different from say, the Azure Maps API docs where [all available query parameters](https://docs.microsoft.com/en-us/rest/api/maps/render/getmapimage#uri-parameters), which are required, etc. are shown. 
Does anyone know where the OCR API Batch Read query parameters are visible? 
Thanks again for the continued engagement!

**Comment by SeaDude** [comment]
Hi @wiazur , 
I'm working through the example you provided (thanks again!). 
I'm no python dev, but so far I have been able to get:
- A Jupyter notebook spun up and your code sample pasted in
- The `computervision` `pip` package installed and imported
- A Computer Vision instance in Azure spun up and my `key` and `endpoint` authenticated in your sample

Stuck on what to do for the `images_list`,  `cropped_images_path`, `working_directory` and `cropped_images_list` in the script...

Will you guide me here?

```
'''
Load and crop images
'''
images_list = []
cropped_images_path = []
working_directory = os.path.dirname(__file__)

# Create an Image object from each image in a directory

for filename in glob.glob('Images\*.jpg'):  # assuming all images are jpg
    imageObject = Image.open(filename)
    images_list.append(imageObject)
    path = os.path.join(working_directory, filename.replace('Images\\', 'CroppedImages\\'))
    cropped_images_path.append(path)

# Optional, draw bounding box around desired line of text, show image
# original_image = Image.open('Images\coffee1.jpg').convert("RGBA")
# draw = ImageDraw.Draw(original_image)
# draw.rectangle(((110, 540), (425, 630)), outline="red")
# original_image.show()
 
# Crop each image in your list at the same place
cropped_images_list = []
for image in images_list:
    # Don't exceed your image height and width
    # w, h = image.size
    # print('Image width & height:', w, h)
    cropped = image.crop((110,540,425,630)) # edges: left, top, right, bottom
    cropped_images_list.append(cropped)

    # Optional, to display cropped image
    cropped.show()

# Save the cropped images
for i in range(len(cropped_images_list)):
    # Convert cropped images back to PIL.JpegImagePlugin.JpegImageFile type
    b = BytesIO()
    cropped_images_list[i].save(b, format="jpeg")
b.close()

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-19-45102c6bc387> in <module>()
     65     cropped_images_list[i].save(b, format="jpeg")
     66 
---> 67 b.close()
     68 
     69 '''

NameError: name 'b' is not defined
```

**Comment by wiazur** [comment]
Hi @SeaDude, yes the API site is not as informative as some others. I think this is because the Batch Read File is still fairly new. I would expect it to be added to that document you sent the link for, at some point. We are using the SDK though, so much of the variance is through the `batch_read_file_in_stream` parameters, which are explained a bit more in the [SDK reference](https://docs.microsoft.com/en-us/python/api/azure-cognitiveservices-vision-computervision/azure.cognitiveservices.vision.computervision.operations.computervisionclientoperationsmixin?view=azure-python#batch-read-file-in-stream-image--custom-headers-none--raw-false--callback-none----operation-config-) and the [SDK source code](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/cognitiveservices/azure-cognitiveservices-vision-computervision/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py)--see the `batch_read_file_in_stream` function.

If I understand you correctly, you are curious to know what to use for `images_list`, `cropped_images_path`, `working_directory` and `cropped_images_list`. The images list would be the images you have, your engineering images, the full image (you can always change the image type to PNG if needed in the code, it's currently set to use JPGs). The cropped images are created by the script, so you don't need to provide anything, just create a folder for them if you haven't already. If you've created and placed the folders named _Images_ and _CroppedImages_ in your working directory, the code is all set to withdraw from and put images into these folders, so you would not need to change any of the path variables. The working directory is the name of the directory your python script is in and where you'll put your 2 images folders.

Btw, is there a better language you would like to use? This SDK is available in C#, Java, and Node too. Since we create all our samples in these languages, I could create specific Batch Read File samples for them too.

Let me know if you need more information, thanks!

**Comment by SeaDude** [comment]
Awesome info @wiazur, you're the best! 
1. I'll add *Images* and *CroppedImages* folders to my working directory
2. I'll populate *Images* with some sample images (they're actually multipage PDF's, which will be interesting, but I'll figure it out)
3. I'll move the `b = BytesIO()` into the loop and see if that helps. I'm using [Azure Notebooks](https://notebooks.azure.com/) so still getting my directory structure down

**RE:** `... is there a better language you would like to use? `:
- I'm a PowerPlatform (low-ish code) guy (PowerApps, PowerAutomate, PowerBI) so I'm used to creating a [Custom Connector](https://docs.microsoft.com/en-us/connectors/custom-connectors/use-custom-connector-powerapps) (API wrapper) and hitting API's then displaying responses in PowerApps/parsing responses in PowerAutomate.
- I'm also very proficient with [PostMan ](https://www.postman.com/)for testing API's and chaining responses-requests together to perform quasi-app workflows before implementing.
- I've dabbled with Jupyter Notbooks and the associated libraries (`[requests](https://2.python-requests.org/en/master/)`) for making api calls and manipulating responses in data vis tools like `Altair`, but I'm rudimentary at best in Python.

Will report back on progress~! Thanks again!

**Comment by wiazur** [comment]
Glad to help!

There is also a way to add a PDF stream, if that helps. See code below.

```
'''
Read and extract from the image
'''
def pdf_text():
    # Images PDF with text
    filepath = open('TextImages.pdf','rb')

    # Async SDK call that "reads" the image
    response = client.batch_read_file_in_stream(filepath, raw=True)

    # Don't forget to close the file
    filepath.close()

    # Get ID from returned headers
    operation_location = response.headers["Operation-Location"]
    operation_id = operation_location.split("/")[-1]

    # SDK call that gets what is read
    while True:
        result = client.get_read_operation_result(operation_id)
        if result.status not in ['NotStarted', 'Running']:
            break
        time.sleep(1)
    return result

'''
Display extracted text and bounding box
'''
# Displays text captured and its bounding box (position in the image)
result = pdf_text()
if result.status == TextOperationStatusCodes.succeeded:
    for textResult in result.recognition_results:
        for line in textResult.lines:
            print(line.text)
            #print(line.bounding_box)
```
