### ISSUE TITLE
Error shown in Ink recogniser java app 

### ISSUE THREAD

**Issue by bindug11** [Azure-Samples/cognitive-services-REST-api-samples#111]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> git cloned cognitive services-REST-api-samples and then navigated to the project java/inkRecognition/android-sample-app, Built successfully through android studio and connected an android phone and it runs successfully. Opened a recognizer app in the android device and after writing on it gave the below error.

### Any log messages given by the failure
> Code: JSON ErrorMessage: Exception Thrown During JSON Error Handling Target: JSONDetails

### Expected/desired behavior
> To show the recognized output.

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
MacOs(Sierra)
### Versions
> 10.14.4

### Mention any other details that might be useful
Android version 8.1.0
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by wiazur** [comment]
Hi @bindug11, apologies for the delay. Are you still having this issue? I ran the code in a virtual device both from the Android Studio project and the app in the device, but both work in Windows 10. Could you list your Android Studio versions and the device you used? Also the full stacktrace might help, thanks.
