### ISSUE TITLE
SearchResults not found anywhere

### ISSUE THREAD

**Issue by TinchoMza** [Azure-Samples/cognitive-services-REST-api-samples#17]
On the introduction code, there is this line:

SearchResults results = new SearchResults(new HashMap<String, String>(), response);

I added all the imports, but this class does not exist. Using Java SE Dev Kit  8 update 191 64-bit.

**Comment by aahill** [comment]
Hi @TinchoMza, I'm just now seeing this - could you let me know which sample you're working on? I'll take a look once I know that. Thanks!

**Comment by TinchoMza** [comment]
Oh, I meant the "SearchResults" class. There is no such method on java.
