### ISSUE TITLE
Tags changed for description of a person laid on the floor. Description used to contain "lay" if image comprised a person on the floor. This is no longer the case.

### ISSUE THREAD

**Issue by chrisnurse** [Azure-Samples/cognitive-services-REST-api-samples#37]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [x] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Capture an image and submit to vision service to return tags. Tags do not contain a version of a word synonymous with "lay", "laid down", "fallen", etc.

### Any log messages given by the failure
> None

### Expected/desired behavior
> One of the tags should indicate the orientation or position of a person..."laying", "standing", "sitting", or similar

### OS and Version?
> Any Windows - mine is UWP

### Versions
> Current Cognitive services API

### Mention any other details that might be useful

I first built a prototype in 2017, and tested the image description capabilities of Google and MS Cognitive services. For my use case MS was better, simply because both services would say they saw a person, but only Microsoft reported "lay" as in "laid down".

This was critical to my progressing discussion of using Cognitive Services to prototype home care devices.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by wiazur** [comment]
Hi @chrisnurse, thanks for the feature request. It's unknown if this will be implemented in the future at this time, but I wanted to point out that there is another way of finding out the position of a person in an image. Sometimes in a description, it will say what the person is doing.

For instance, if you send [this image](https://bcpharmacy.files.wordpress.com/2012/03/lastlong-with-sitting.jpg) to the API, it will say:
`a man sitting in front of a window with confidence 0.5809454581580495`

[This image](https://c1.staticflickr.com/9/8657/28235682532_aa60be70a7_b.jpg) also gives a description: 
`a young man lying on the grass with confidence 0.792376616131881`

In [this image](https://get.pxhere.com/photo/back-view-black-and-white-buildings-city-cityscape-coat-downtown-guy-male-man-monochrome-outdoors-person-perspective-skyscrapers-standing-trench-coat-urban-wear-1549999.jpg), there is a description of standing:
`a man standing on a sidewalk with confidence 0.9378039677317365`

So if you parsed the description string, you'd be able to identify these actions in a photo. <br>
I hope this helps.

**Comment by wiazur** [comment]
@chrisnurse, upon further inquiry into the Computer Vision SDK, I see they actually still have these tags in there. As a whole, the newer SDK has tried to take a lot of properties out of the AnalyzeImage() API call, and create separate functions for them. For instance, I see that in [DescribeImageAsync()](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cognitiveservices.vision.computervision.computervisionclientextensions.describeimageasync?view=azure-dotnet#Microsoft_Azure_CognitiveServices_Vision_ComputerVision_ComputerVisionClientExtensions_DescribeImageAsync_Microsoft_Azure_CognitiveServices_Vision_ComputerVision_IComputerVisionClient_System_String_System_Nullable_System_Int32__System_String_System_Threading_CancellationToken_), there are properties Captions, Metadata, and Tags.

I ran some image URLs in a sample and I got some actions in the tags that a person was doing. For instance with the person standing, I got these person-related tags: standing, holding, walking. Below is a code sample if you wanted to run it.

```
using System;
using Microsoft.Azure.CognitiveServices.Vision.ComputerVision;
using Microsoft.Azure.CognitiveServices.Vision.ComputerVision.Models;
using System.Threading.Tasks;

namespace DescribeImageAsync
{
    class Program
    {
        static string personStanding = "https://get.pxhere.com/photo/back-view-black-and-white-buildings-city-cityscape-coat-downtown-guy-male-man-monochrome-outdoors-person-perspective-skyscrapers-standing-trench-coat-urban-wear-1549999.jpg";
        static string personLaying = "https://il8.picdn.net/shutterstock/videos/16689553/thumb/7.jpg";
        static string personSitting = "https://i.pinimg.com/736x/62/ae/d3/62aed3bde181347daca11e1d768a8957--photoshop-images-cut-out-people.jpg";

        static string SubscriptionKey = Environment.GetEnvironmentVariable("COMPUTER_VISION_SUBSCRIPTION_KEY");
        static string Endpoint = Environment.GetEnvironmentVariable("COMPUTER_VISION_ENDPOINT");


        static void Main(string[] args)
        {
            ComputerVisionClient client = Authenticate(Endpoint, SubscriptionKey);

            DescribeImage(client, personStanding).Wait();
            DescribeImage(client, personLaying).Wait();
            DescribeImage(client, personSitting).Wait();

        }

        public static ComputerVisionClient Authenticate(string endpoint, string key)
        {
            ComputerVisionClient client =
                new ComputerVisionClient(new ApiKeyServiceClientCredentials(key))
                { Endpoint = endpoint };
            return client;
        }

        public static async Task DescribeImage(ComputerVisionClient client, string url)
        {
            ImageDescription results = await client.DescribeImageAsync(url);

            Console.WriteLine();
            Console.WriteLine("Captions:");
            foreach (var caption in results.Captions)
            {
                Console.WriteLine(caption.Text);
            }

            Console.WriteLine();
            Console.WriteLine("Metadata:");
            Console.WriteLine("Format" + results.Metadata.Format);
            Console.WriteLine("Height" + results.Metadata.Height);
            Console.WriteLine("Width" + results.Metadata.Width);

            Console.WriteLine();
            Console.WriteLine("Tags:");
            foreach (var tag in results.Tags)
            {
                Console.WriteLine(tag);
            }
        }
    }
}
```
